on: [push]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout master branch
           uses: actions/checkout@master

         - name: Build Docker images
           run: |
             sleep 10

         - name: Push Docker images
           run: |
             sleep 10

         - name: Install kubectl
           uses: azure/setup-kubectl@v3.0

         - name: Set kubectl context
           uses: Azure/k8s-set-context@v3.0
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - name: Deploy jwt-secret to k8s
           uses: Azure/k8s-deploy@v4.4
           with:
              action: deploy
              strategy: basic
              namespace: connor-test
              manifests: |
                 extras/jwt/jwt-secret.yaml

         - name: Deploy Application to k8s and make sure they are in a ready state
           uses: Azure/k8s-deploy@v4.4
           with:
              action: deploy
              strategy: basic
              namespace: connor-test
              manifests: |
                 kubernetes-manifests/accounts-db.yaml
                 kubernetes-manifests/balance-reader.yaml
                 kubernetes-manifests/config.yaml
                 kubernetes-manifests/contacts.yaml
                 kubernetes-manifests/frontend.yaml
                 kubernetes-manifests/ledger-db.yaml
                 kubernetes-manifests/ledger-writer.yaml
                 kubernetes-manifests/loadgenerator.yaml
                 kubernetes-manifests/transaction-history.yaml
                 kubernetes-manifests/userservice.yaml